################################################## 
# BulkOpportunityService_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from BulkOpportunityService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class BulkOpportunityServiceLocator:
    BulkOpportunityServiceInterface_address = "https://adwords.google.com:443/api/adwords/o/v201101/BulkOpportunityService"
    def getBulkOpportunityServiceInterfaceAddress(self):
        return BulkOpportunityServiceLocator.BulkOpportunityServiceInterface_address
    def getBulkOpportunityServiceInterface(self, url=None, **kw):
        return BulkOpportunityServiceSoapBindingSOAP(url or BulkOpportunityServiceLocator.BulkOpportunityServiceInterface_address, **kw)

# Methods
class BulkOpportunityServiceSoapBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # get: getBulkOpportunity
    def getBulkOpportunity(self, request):
        if isinstance(request, getBulkOpportunityRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(getBulkOpportunityResponse.typecode)
        return response

getBulkOpportunityRequest = ns1.getBulkOpportunity_Dec().pyclass

getBulkOpportunityResponse = ns1.getBulkOpportunityResponse_Dec().pyclass
