################################################## 
# CampaignCriterionService_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from CampaignCriterionService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class CampaignCriterionServiceLocator:
    CampaignCriterionServiceInterface_address = "https://adwords.google.com:443/api/adwords/cm/v200909/CampaignCriterionService"
    def getCampaignCriterionServiceInterfaceAddress(self):
        return CampaignCriterionServiceLocator.CampaignCriterionServiceInterface_address
    def getCampaignCriterionServiceInterface(self, url=None, **kw):
        return CampaignCriterionServiceSoapBindingSOAP(url or CampaignCriterionServiceLocator.CampaignCriterionServiceInterface_address, **kw)

# Methods
class CampaignCriterionServiceSoapBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # get: getCampaignCriterion
    def getCampaignCriterion(self, request):
        if isinstance(request, getCampaignCriterionRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(getCampaignCriterionResponse.typecode)
        return response

    # mutate: getCampaignCriterion
    def mutateCampaignCriterion(self, request):
        if isinstance(request, mutateCampaignCriterionRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(mutateCampaignCriterionResponse.typecode)
        return response

getCampaignCriterionRequest = ns0.getCampaignCriterion_Dec().pyclass

getCampaignCriterionResponse = ns0.getCampaignCriterionResponse_Dec().pyclass

mutateCampaignCriterionRequest = ns0.mutateCampaignCriterion_Dec().pyclass

mutateCampaignCriterionResponse = ns0.mutateCampaignCriterionResponse_Dec().pyclass
