################################################## 
# CustomerSyncService_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from CustomerSyncService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class CustomerSyncServiceLocator:
    CustomerSyncServiceInterface_address = "https://adwords.google.com:443/api/adwords/ch/v201008/CustomerSyncService"
    def getCustomerSyncServiceInterfaceAddress(self):
        return CustomerSyncServiceLocator.CustomerSyncServiceInterface_address
    def getCustomerSyncServiceInterface(self, url=None, **kw):
        return CustomerSyncServiceSoapBindingSOAP(url or CustomerSyncServiceLocator.CustomerSyncServiceInterface_address, **kw)

# Methods
class CustomerSyncServiceSoapBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # get: getCustomerSync
    def getCustomerSync(self, request):
        if isinstance(request, getCustomerSyncRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(getCustomerSyncResponse.typecode)
        return response

getCustomerSyncRequest = ns1.getCustomerSync_Dec().pyclass

getCustomerSyncResponse = ns1.getCustomerSyncResponse_Dec().pyclass
